export default {
  Logo: require('../assets/logo.png'),
  Placeholder: require('../assets/placeholder.png'),
  upload: require('../assets/upload.png'),
  // edumate: require('../assets/edumate.png'),
  // Banner2: require('../assets/banner2.png'),
  BackIcon: require('../assets/backIcon.png'),
  home_tuition: require('../assets/home_tuition.jpeg'),
  higher_study: require('../assets/higher_study.png'),
  books: require('../assets/books.png'),
  machine_learning: require('../assets/machine_learning.png'),
  pharmacy: require('../assets/pharmacy.png'),
  basic_grammar: require('../assets/basic_grammar.png'),
  search: require('../assets/search.png'),
  audios: require('../assets/audios.png'),
  games: require('../assets/games.png'),
  videos: require('../assets/videos.png'),
  articles: require('../assets/articles.png'),
  Calender: require('../assets/calender.png'),
}
